### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by solcanmihai** [andreigasparovici/cerc-info#15]
like always

**Comment by andreigasparovici** [comment]
_Ask and ye shall receive_

Solved in 7a3b908da23850b4733b1ec39fef215a1034f434

**Comment by solcanmihai** [comment]
Still not working. I have to use the cors plugin on chrome to be able to use the api.

**Comment by andreigasparovici** [comment]
Add the error here. The CORS is configured as it always is, so it would be useful to see the error.

**Comment by solcanmihai** [comment]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/api/login. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).`
There ya go.

**Comment by solcanmihai** [comment]
Turns out it was a firefox bug. Worked after you specified the values, instead of adding '*'
